name: Build / Test / Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - uses: pnpm/action-setup@v4
        name: Install PNPM
        id: pnpm-install
        with:
          version: 9.5
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build
        run: pnpm prepare

      - name: Test
        run: pnpm test

      - name: Lint
        run: pnpm lint